services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8080:80
        volumes:
            - "D:/OneDrive/SoftUni/DevOps/m1-01-2023/HomeWork3/newapp/web:/var/www/html:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network: